language: cpp
compiler: gcc
dist: xenial
notifications:
  email: false

addons:
  apt:
    packages: lcov

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90

  # Install coverals gem for uploading coverage to coveralls.
  - gem install coveralls-lcov

before_script:
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build

script:
  - cd $PARENTDIR/build
  - cmake -DCMAKE_BUILD_TYPE=Coverage $PARENTDIR
  - make
  - make coverage

after_success:
  - cd $PARENTDIR/build
  - lcov --list coverage_out.info.cleaned  # Show test report in travis log.
  - coveralls-lcov coverage_out.info.cleaned  # uploads to coveralls

